if(NOT DEFINED DESKTOP_TODO_VERSION OR DESKTOP_TODO_VERSION STREQUAL "")
  set(DESKTOP_TODO_VERSION "2.0.0")
endif()

if(NOT DESKTOP_TODO_VERSION MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
  message(FATAL_ERROR "DESKTOP_TODO_VERSION must be semantic MAJOR.MINOR.PATCH (got '${DESKTOP_TODO_VERSION}')")
endif()

set(DESKTOP_TODO_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(DESKTOP_TODO_VERSION_MINOR "${CMAKE_MATCH_2}")
set(DESKTOP_TODO_VERSION_PATCH "${CMAKE_MATCH_3}")
foreach(component IN ITEMS DESKTOP_TODO_VERSION_MAJOR DESKTOP_TODO_VERSION_MINOR DESKTOP_TODO_VERSION_PATCH)
  if(${component} GREATER 65535)
    message(FATAL_ERROR "${component} exceeds the Windows VERSIONINFO limit of 65535")
  endif()
endforeach()

set(DESKTOP_TODO_FILE_VERSION
  "${DESKTOP_TODO_VERSION_MAJOR},${DESKTOP_TODO_VERSION_MINOR},${DESKTOP_TODO_VERSION_PATCH},0")
set(DESKTOP_TODO_FILE_VERSION_DOTTED "${DESKTOP_TODO_VERSION}.0")
